### ISSUE TITLE
Where is the docker-compose.dev.yml?

### ISSUE THREAD

**Issue by oscanog** [mhelmer/dockerize-uwsgi-nginx-webpack#3] opened 2016-10-09 03:16 UTC
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose.dev.yml'

**Comment by mhelmer** [comment] 2016-10-09 04:14
Hi,

I have updated the structure, but forgot the README. Basically you have one base compose file now, which you will override depending on environment.

In dev, you will just use eg `docker-compose <args>` which will use `docker-compose.yml` and `docker-compose.override.yml`.

For production it would be: `docker-compose -f docker-compose.yml -f docker-compose.prod.yml <args>`

**Comment by oscanog** [comment] 2016-10-09 04:33
I run 
`docker-compose -f docker-compose.yml -f docker-compose.prod.yml build` 
finished building
then
`docker-compose -f docker-compose.yml -f docker-compose.prod.yml run django ./bootstrap-dev`

got an error
File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/srv/django/project/settings/prod.py", line 3, in <module>
    DEBUG=false
NameError: name 'false' is not defined

## I think the error is 'false', it must be 'False'

**Comment by mhelmer** [comment] 2016-10-09 04:40
Yeah, it should be `False`. You probably want to set `ALLOWED_HOSTS` and a different `SECRET_KEY` in there as well.

**Comment by oscanog** [comment] 2016-10-09 05:21
```
File "/srv/django/.env/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/srv/django/static/admin'
```

Got a permission error in collectstatic.
both in development and production.

I did chown the root directory, same error occurred.
May I know what OS are you using?

**Comment by mhelmer** [comment] 2016-10-09 05:33
I'm on debian, but I have also used projects based on this on os x and gentoo.
I think the issue is that docker volumes are owned by root when they are ceeated and the django/react containers run as uid 1000.

Run `docker-compose run ngnix chown -R 1000:1000 /srv/*` before collectstatic

**Comment by oscanog** [comment] 2016-10-09 05:56
![error](https://cloud.githubusercontent.com/assets/20588485/19218253/db153ea6-8e27-11e6-9eae-daf4975f290b.jpg)

### Got it working, but return some error, here's the chrome console.

and some missing module of `djangorestframework-jwt`

**Comment by mhelmer** [comment] 2016-10-09 06:03
Cheers! Thanks for reporting. The chrome 'error' is just a warning because redux-form fields contains props that are not valid for dom-elements.

Redux-form 6 does things a bit differently and avoids this problem,  so I should update/migrate.

**Comment by oscanog** [comment] 2016-10-09 06:10
I'll wait for the update, just play with your current build for now.
BTW, thanks for this. this is very neat boilerplate for django react webpack + docker

**Comment by mhelmer** [comment] 2016-10-09 08:58
I addressed the above problems, but didn't migrate redux-form yet. So, I will close this one and take care of redux-form for in #4

**Closed as completed by mhelmer** 2016-10-09 08:58 UTC
